config/routes.rb
Splurty::Application.routes.draw do

  root 'quotes#index'

  resources :quotes

  get 'about', to: 'quotes#about'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :saying, presence: true, length: {maximum: 140, minimum:3}
  validates :author, presence: true, length: {maximum: 50, minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = "<strong>Could not save</strong> the data you entered is invalid."
    end
    redirect_to root_path
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Splurty</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="col-xs-3">
      <%= link_to root_path, class: "logo" do %>
        <div class="circle">
          <br />
          You know
          <br />
          you need
          <br />
          to code
        </div>
      <% end %>
    </div>
    <div class="col-sm-4 hidden-xs slogan">
      Increasing mental strength one quote at a time 
    </div>
    <div class="col-xs-8 col-xs-offset-1 col-sm-offset-0 col-sm-5 links">
      <!-- Button trigger modal -->
      <%= link_to 'Contribute', '#', data: {toggle:"modal", target:"#myModal"}%>
      &nbsp;&nbsp;
      <%= link_to 'About', about_path %>
    </div>
  </header>



  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Enter a quote</h4>
        </div>      
          <div class="modal-body">
            <%= simple_form_for Quote.new do |f| %>
              <%= f.input :saying, label: "Which quote would you like to add?", placeholder: "The secret of getting ahead is getting started" %>
              <br />
              <%= f.input :author, label: "Who is the author?", placeholder: "Mark Twain" %>
              <div class="modal-footer">
                <%= f.submit "Add quote", class: "btn btn-danger"%>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>



  <hr />

  <br class='clear' />  

<div class="container">
  <% if flash[:error].present? %>
    <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
      <%= flash[:error].html_safe %>
    </div>
  <% end %>

  <%= yield %>
</div>

<div class="footer">
  <div class="container">
    <div class="col-xs-12 col-sm-6">
      <%= link_to "This isn´t enough, I need more", root_path, class: "next-quote" %>
    </div>
    <div class="col-xs-12 col-sm-6 footer-blurb">
      Proudly hacked somewhere in the world by Elmer 
      <br /> 
      Want to build your own Splurty Web App - <a href="http://thefirehoseproject.com">Learn how to code here</a>
    </div>
</div>


</body>
</html>

app/views/quotes/about.html.erb
<div class="col-xs-10 col-xs-offset-1 about">
  <h1>About Splurty</h1>

  <p>
    Splurty was built by <a target="_blank" href="https://github.com/efesantos"> Elmer</a>
  </p>
  <br />
  <p>
    If you want to start coding - do it <a target="_blank" href="http://thefirehoseproject.com"> here</a>
  </p>

  <div class="col-xs-12 col-sm-4">
    <%= image_tag 'profile.jpg', class: 'img-responsive' %>
  </div>

  <div class="col-xs-12 col-sm-7 col-sm-offset-1">
    <h2 class="text-center">Elmer Santos</h2>
    <br />
    <p>
      Elmer is a soon-to-be web developer, entrepreneur and life-long learner
    </p>
  </div>

  <br class="clear"/>
  <br />
  <br />
  <br />
  <br />



</div>

app/views/quotes/index.html.erb
<h2>
  <span>SPLURTY / No. <%= @quote.id %> </span>
  Here´s the <u>best unsolicited startup advice</u> you can get!
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="pull-right"><%= @quote.author %></h2>

<br class="clear"/>
<br />
<br />
<br />
<br />